name: PHP Unit

on:
  push:
    branches:
      - '**'
  pull_request:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:

jobs:
  settings:
    name: Collect settings
    runs-on: ubuntu-latest
    outputs:
      php-versions: ${{ steps.php-versions.outputs.value }}
      extensions: ${{ steps.extensions.outputs.value }}
      dependencies: ${{ steps.dependencies.outputs.value }}
      laravel-versions: ${{ steps.laravel-versions.outputs.value }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: Detect dependencies versions
        id: dependencies
        run: |
          DEPS_HIGHEST="highest"
          DEPS_LOCKED="$(if [ -f "composer.lock" ] && [ ! "$GITHUB_EVENT_NAME" == "schedule" ]; then echo "locked"; fi)"
          DEPS_LOWEST="$(if [ ! "$GITHUB_EVENT_NAME" == "schedule" ]; then echo "lowest"; fi)"
          echo "::set-output name=value::$(echo "[\"$DEPS_HIGHEST\", \"$DEPS_LOCKED\", \"$DEPS_LOWEST\"]" | jq "[.[] | select(length > 0)]" -r -c)"
      - name: Detect PHP versions
        id: php-versions
        run: |
          mkdir "$RUNNER_TEMP/easy-ci"
          composer require --no-interaction --working-dir="$RUNNER_TEMP/easy-ci" --update-no-dev symplify/easy-ci
          echo "::set-output name=value::$("$RUNNER_TEMP/easy-ci/vendor/bin/easy-ci" php-versions-json)"
      - name: Detect PHP extensions
        id: extensions
        run: |
          echo "::set-output name=value::$(jq '[.require, ."require-dev", .suggest] | add | to_entries | map(select(.key | match("ext-";"i"))) | map(.key | sub("ext-"; "")) | join(", ")' -r -c composer.json)"
      - name: Detect Laravel versions
        id: laravel-versions
        run: |
          echo "::set-output name=value::$(jq '.require."laravel/framework" | split("|")' -c composer.json)"

  phpunit:
    name: "Laravel ${{ matrix.laravel }} / PHP ${{ matrix.php }} (${{ matrix.os }} / ${{ matrix.dependencies }})"

    runs-on: ${{ matrix.os }}
    needs:
      - settings

    # `continue-on-error: true` will add a red mark in commit/pr, this is
    # definitely not what I want :( So we exclude some items instead.
    #
    # https://github.com/actions/toolkit/issues/399
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php: ${{ fromJson(needs.settings.outputs.php-versions) }}
        laravel: ${{ fromJson(needs.settings.outputs.laravel-versions) }}
        dependencies: ${{ fromJson(needs.settings.outputs.dependencies) }}
        exclude:
          - dependencies: 'lowest'
            php: ${{ fromJson(needs.settings.outputs.php-versions)[1] }}
          - dependencies: 'lowest'
            php: ${{ fromJson(needs.settings.outputs.php-versions)[2] }}
          - dependencies: 'lowest'
            php: ${{ fromJson(needs.settings.outputs.php-versions)[3] }}

    steps:
      # Required to avoid converting LF into CRLF on Windows or some tests will
      # fail.
      - name: Disable core.autocrlf
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ needs.settings.outputs.extensions }}

      # On Windows, the caret ^ is the escape character, so the version string
      # that contains ^ will be handled incorrectly
      - name: Install Laravel
        shell: bash
        run: |
          composer remove --no-interaction --no-progress --ansi --no-update laravel/framework
          composer require --no-interaction --no-progress --ansi --no-update "laravel/framework:${{ matrix.laravel }}"

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Execute
        run: |
          vendor/bin/phpunit
