github:
  release: true

git:
  changelog: false

npm:
  publish: false

hooks:
  "before:init":
    - "composer run-script phpunit"
    - "composer run-script phpcs"

plugins:
  "@release-it/bumper":
    in:
      file: metadata.json
    out:
      file: packages/*/metadata.json
