npm:
  publish: false

hooks:
  "before:init":
    - "composer run-script phpunit"
    - "composer run-script phpcs"

plugins:
  "@release-it/bumper":
    out:
      file: packages/*/metadata.json
  "@release-it/conventional-changelog":
    "preset": conventionalcommits
    "infile": CHANGELOG.md
