#!/usr/bin/env php
<?php

use Illuminate\Contracts\Console\Kernel as ConsoleKernelContract;
use Illuminate\Contracts\Debug\ExceptionHandler as ExceptionHandlerContract;
use Illuminate\Foundation\Application;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

# Debug
define('LARAVEL_START', microtime(true));

// Auto Loader
require __DIR__.'/vendor/autoload.php';

// Boot
$app = new Application(__DIR__);

$app->singleton(
    ConsoleKernelContract::class,
    ConsoleKernel::class,
);
$app->singleton(
    ExceptionHandlerContract::class,
    ExceptionHandler::class
);

// Run
$input  = new ArgvInput();
$kernel = $app->make(ConsoleKernelContract::class);
$status = $kernel->handle($input, new ConsoleOutput());

// Shutdown
$kernel->terminate($input, $status);

exit($status);
