name: Checkout
description: Checkout the project or the package.

inputs:
  package:
    description: "Package path to checkout."
    required: false
    type: string

runs:
  using: composite
  steps:
    # Required to avoid converting LF into CRLF on Windows or some tests will fail.
    - name: Disable core.autocrlf
      shell: bash
      run: |
        git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{ inputs.package && '.repo' || '' }}

    # The `.git` directory is required for Composer to resolve `self.version`.
    - name: Select Package
      if: ${{ inputs.package }}
      shell: bash
      run: |
        cp -R "./.repo/.git" .
        cp -R "./.repo/${{ inputs.package }}/." .
