name: 'Install PHP'
description: 'Install PHP and dependencies'

inputs:
  version:
    description: "PHP Version (version string, 'lowest', or empty)"
    required: false
    type: string
  dependencies:
    description: "Should requirements be installed via composer or not (default `true`)"
    required: false
    type: boolean
    default: true
  working-directory:
    description: "The directory where `composer.json` is located (default repository root)."
    required: false
    type: string
    default: ""

runs:
  using: composite
  steps:
    - name: Detect PHP version
      id: version
      if: ${{ ! inputs.version || inputs.version == 'lowest'}}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "value=$(jq '"^8.3|" + .require."php" | split("|") | map(select(. != "")) | sort | (if "${{ inputs.version }}" == "lowest" then first else last end) | sub("^[^\\d]+"; "")' -r -c composer.json)" >> $GITHUB_OUTPUT

    - name: Detect required PHP extensions
      id: extensions
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # The list of extensions can be generated via the following command:
        #
        #     composer check-platform-reqs --format=json | jq -c '. | map(.name) | map(select(.|startswith("ext-"))) | map(. | sub("ext-"; "")) | unique | sort'
        #
        # Unfortunately, when no `composer.lock` there is no way to get the list
        # before installing PHP and dependencies.

        echo 'value=["bcmath","ctype","dom","fileinfo","filter","hash","iconv","intl","json","libxml","mbstring","openssl","pcre","pdo_sqlite","phar","session","tokenizer","xml","xmlreader","xmlwriter"]' >> $GITHUB_OUTPUT

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.version && inputs.version != 'lowest' && inputs.version || steps.version.outputs.value}}
        extensions: ${{ join(fromJSON(steps.extensions.outputs.value)) }}
        coverage: none
        tools: cs2pr

    - name: Install dependencies
      if: ${{ inputs.dependencies == 'true' || inputs.dependencies == 1 }} # https://github.com/actions/runner/issues/1483
      uses: ramsey/composer-install@v3
      with:
        working-directory: ${{ inputs.working-directory }}

    - name: Setup problem matchers
      shell: bash
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
