name: Feature request
description: New feature wanted!
labels: ["scope: feat"]
body:
  - type: dropdown
    attributes:
      label: Package
      description: "Please choose a package, leave blank if it is general or if you are not sure."
      options:
        - glob-matcher
        - graphql-printer
        - lara-asp-core
        - lara-asp-dev
        - lara-asp-documentator
        - lara-asp-eloquent
        - lara-asp-formatter
        - lara-asp-graphql
        - lara-asp-graphql-testing
        - lara-asp-migrator
        - lara-asp-serializer
        - lara-asp-spa
        - lara-asp-testing
        - path
        - phpunit-extensions
        - phpunit-graphql
        - phpunit-xml
        - text-parser
  - type: textarea
    attributes:
      label: Description
      placeholder: Type your idea/suggestion here…
    validations:
      required: true
