name: 'Checkout'

inputs:
  package:
    description: "Package path to checkout."
    required: false
    type: string

runs:
  using: composite
  steps:
    # Required to avoid converting LF into CRLF on Windows or some tests will fail.
    - name: Disable core.autocrlf
      run: git config --global core.autocrlf false

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: ${{ inputs.package && '.repo' || '' }}

    - name: Select Package
      if: ${{ inputs.package }}
      run: |
        cp -R "./.repo/${{ inputs.package }}/." .
