name: PHP Code Sniffer

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      php-extensions:
        description: "The comma separated list of required php extensions."
        required: true
        type: string

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Disable core.autocrlf
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.php-extensions }}
          tools: cs2pr
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
      - name: Execute
        run: |
          vendor/bin/phpcs --report=checkstyle | cs2pr
