name: Continuous Integration

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
    - cron: "0 0 * * SAT"
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  settings:
    name: Settings
    uses: ./.github/workflows/settings.yml

  monorepo:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: ./.github/actions/php
      - name: Execute
        run: |
          ./vendor/bin/monorepo-builder validate

  phpcs:
    name: Coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: ./.github/actions/php
      - name: Execute
        run: |
          ./vendor/bin/phpcs --report=checkstyle | cs2pr

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: ./.github/actions/php
      - name: Execute
        run: |
          ./vendor/bin/phpstan analyse

  phpunit:
    name: Tests
    uses: ./.github/workflows/phpunit.yml
    with:
      runs-on: '["ubuntu-latest", "windows-latest"]'

  phpunit-package:
    name: Package tests
    needs:
      - settings
      - phpunit
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.settings.outputs.packages-names) }}
    uses: ./.github/workflows/phpunit.yml
    with:
      package: ${{ matrix.package }}
      packages-directory: ${{ needs.settings.outputs.packages-directory }}
