name: Continuous Integration

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
    - cron: "0 0 * * SAT"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  settings:
    name: Settings
    uses: LastDragon-ru/lara-asp/.github/workflows/settings.yml@master

  monorepo:
    name: Validate composer.json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: LastDragon-ru/lara-asp/.github/actions/checkout@master
      - name: Install PHP
        uses: LastDragon-ru/lara-asp/.github/actions/php@master
      - name: Execute
        run: |
          ./vendor/bin/monorepo-builder validate

  phpcs:
    name: Coding standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: LastDragon-ru/lara-asp/.github/actions/checkout@master
      - name: Install PHP
        uses: LastDragon-ru/lara-asp/.github/actions/php@master
      - name: Execute
        run: |
          ./vendor/bin/phpcs --report=checkstyle | cs2pr

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: LastDragon-ru/lara-asp/.github/actions/checkout@master
      - name: Install PHP
        uses: LastDragon-ru/lara-asp/.github/actions/php@master
      - name: Execute
        run: |
          ./vendor/bin/phpstan analyse

  phpunit:
    name: Tests
    uses: LastDragon-ru/lara-asp/.github/workflows/phpunit.yml@master

  phpunit-package:
    name: Package tests
    needs:
      - settings
      - phpunit
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.settings.outputs.packages-names) }}
    uses: LastDragon-ru/lara-asp/.github/workflows/phpunit.yml@master
    with:
      package: ${{ needs.settings.outputs.packages-directory }}/${{ matrix.package }}
