name: Continuous Integration

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  settings:
    uses: ./.github/workflows/settings.yml

  monorepo:
    uses: ./.github/workflows/monorepo.yml

  phpcs:
    uses: ./.github/workflows/phpcs.yml

  phpstan:
    uses: ./.github/workflows/phpstan.yml

  phpunit:
    uses: ./.github/workflows/phpunit.yml

  phpunit-package:
    needs:
      - settings
      - phpunit
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.settings.outputs.packages-names) }}
    uses: ./.github/workflows/phpunit.yml
    with:
      package: ${{ needs.settings.outputs.packages-directory }}/${{ matrix.package }}
