name: Continuous Integration

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
    - cron: "0 0 * * SAT"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  settings:
    uses: ./.github/workflows/settings.yml

  monorepo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout.yml
      - name: Install PHP
        uses: ./.github/actions/php.yml
      - name: Execute
        run: |
          ./vendor/bin/monorepo-builder validate

  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout.yml
      - name: Install PHP
        uses: ./.github/actions/php.yml
      - name: Execute
        run: |
          ./vendor/bin/phpcs --report=checkstyle | cs2pr

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout.yml
      - name: Install PHP
        uses: ./.github/actions/php.yml
      - name: Execute
        run: |
          ./vendor/bin/phpstan analyse

  phpunit:
    uses: ./.github/workflows/phpunit.yml

  phpunit-package:
    needs:
      - settings
      - phpunit
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.settings.outputs.packages-names) }}
    uses: ./.github/workflows/phpunit.yml
    with:
      package: ${{ needs.settings.outputs.packages-directory }}/${{ matrix.package }}
