name: Continuous Integration

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  settings:
    uses: LastDragon-ru/lara-asp/.github/workflows/settings.yml@master

  monorepo:
    uses: ./.github/workflows/monorepo.yml

  phpcs:
    uses: ./.github/workflows/phpcs.yml

  phpstan:
    uses: ./.github/workflows/phpstan.yml

  phpunit:
    uses: ./.github/workflows/phpunit.yml
    needs:
      - settings
