name: Monorepo

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: ./.github/actions/checkout.yml
      - name: Install PHP
        uses: ./.github/actions/php.yml
      - name: Execute
        run: |
          ./vendor/bin/monorepo-builder validate
