name: Sync Packages

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  settings:
    uses: LastDragon-ru/lara-asp/.github/workflows/settings.yml@master

  sync:
    name: "Sync package: ${{ matrix.package }}"
    runs-on: ubuntu-latest
    needs:
      - settings
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.settings.outputs.packages-names) }}
    steps:
      # Dependencies
      - name: Install git-filter-repo
        run: sudo -H pip3 install git-filter-repo
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets[matrix.package] }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Checkout source repo
      - name: Checkout src
        uses: actions/checkout@v3
        with:
          ref: master
          path: src
          fetch-depth: 0

      # Checkout package repo
      # Unfortunately actions/checkout cannot checkout empty repo
      - name: Checkout package
        run: |
          git clone "git@github.com:${{ github.repository }}-${{ matrix.package }}.git" package
      - name: Checkout package (refs/replace)
        working-directory: package
        run: |
          git fetch origin "refs/replace/*:refs/replace/*"

      # Update package
      - name: Update package
        run: |
          git-filter-repo --force --source=src --target=package --subdirectory-filter="${{ needs.settings.outputs.packages-directory }}${{ matrix.package }}"

      # Push
      - name: Push package
        working-directory: package
        run: |
          git push --all --force origin
          git push --tags --force origin
          git push --force origin "refs/replace/*"
