name: PHP Code Sniffer

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: Disable core.autocrlf
        run: git config --global core.autocrlf false
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: ./.github/actions/php.yml
      - name: Execute
        run: |
          ./vendor/bin/phpcs --report=checkstyle | cs2pr
